# Displaying a robot with dynamic eyes
print("Please enter a character for eye")
print()
print("  \\    / ")
print("##########")
print("# o    o #")
print("#  ----  #")
print("##########")
print(" #      # ")
print(" #      # ")
print(" #      # ")
character = input()
print()
print("  \\    / ")
print("##########")
print("# ", character," o  #")
print("#  ----  #")
print("##########")
print(" #      # ")
print(" #      # ")
print(" #      # ")